---
- name: added in 2.4, previously you used 'include'
  import_tasks: vpc.yml
  when: eks_cluster is defined

- name: 'aws vpc tasks - teardown'
  include: tasks/eks-rm.yml   
  when: eks_cluster is not defined 
